spring:
  application:
    name: USER-API

  sleuth:
    sampler:
      percentage: 1.0

  data:
    mongodb:
      host: 192.168.99.100
      port: 32769

server:
  port: 8080

eureka:
  client:
    registry-fetch-interval-seconds: 60
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8090/eureka}
    enabled: true # for dev
  instance:
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: false